<?php

namespace ContainerTr3c8Q1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RRg9FrdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RRg9Frd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RRg9Frd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'messageService' => ['privates', 'App\\Service\\MessageService', 'getMessageServiceService', true],
            'roomService' => ['privates', 'App\\Service\\RoomService', 'getRoomServiceService', true],
        ], [
            'messageService' => 'App\\Service\\MessageService',
            'roomService' => 'App\\Service\\RoomService',
        ]);
    }
}
