<?php

namespace ContainerTr3c8Q1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZtLPLlQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ztLPLlQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ztLPLlQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ChatController::getLastMessages' => ['privates', '.service_locator.RRg9Frd', 'get_ServiceLocator_RRg9FrdService', true],
            'App\\Controller\\ChatController::index' => ['privates', '.service_locator.9XMxz60', 'get_ServiceLocator_9XMxz60Service', true],
            'App\\Controller\\ChatController::manageInstantMessage' => ['privates', '.service_locator.RRg9Frd', 'get_ServiceLocator_RRg9FrdService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\RoomController::index' => ['privates', '.service_locator.9XMxz60', 'get_ServiceLocator_9XMxz60Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\ChatController:getLastMessages' => ['privates', '.service_locator.RRg9Frd', 'get_ServiceLocator_RRg9FrdService', true],
            'App\\Controller\\ChatController:index' => ['privates', '.service_locator.9XMxz60', 'get_ServiceLocator_9XMxz60Service', true],
            'App\\Controller\\ChatController:manageInstantMessage' => ['privates', '.service_locator.RRg9Frd', 'get_ServiceLocator_RRg9FrdService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\RoomController:index' => ['privates', '.service_locator.9XMxz60', 'get_ServiceLocator_9XMxz60Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\ChatController::getLastMessages' => '?',
            'App\\Controller\\ChatController::index' => '?',
            'App\\Controller\\ChatController::manageInstantMessage' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RoomController::index' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\ChatController:getLastMessages' => '?',
            'App\\Controller\\ChatController:index' => '?',
            'App\\Controller\\ChatController:manageInstantMessage' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RoomController:index' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
