<?php

namespace ContainerTr3c8Q1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessageServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\MessageService' shared autowired service.
     *
     * @return \App\Service\MessageService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/MessageService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/UserService.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService'));

        return $container->privates['App\\Service\\MessageService'] = new \App\Service\MessageService($a, new \App\Service\UserService($a));
    }
}
