<?php

namespace ContainerTr3c8Q1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRoomServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\RoomService' shared autowired service.
     *
     * @return \App\Service\RoomService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/RoomService.php';

        return $container->privates['App\\Service\\RoomService'] = new \App\Service\RoomService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Service\\MessageService'] ?? $container->load('getMessageServiceService')));
    }
}
