<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'chat' => [['id'], ['id' => 0, '_controller' => 'App\\Controller\\ChatController::index'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/chat']], [], []],
    'manageMessage' => [[], ['_controller' => 'App\\Controller\\ChatController::manageInstantMessage'], [], [['text', '/manageInstantMessage']], [], []],
    'lastMessages' => [['idRoom'], ['idRoom' => 0, '_controller' => 'App\\Controller\\ChatController::getLastMessages'], [], [['variable', '/', '[^/]++', 'idRoom', true], ['text', '/getLastMessages']], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], []],
    'room' => [[], ['_controller' => 'App\\Controller\\RoomController::index'], [], [['text', '/room']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\DefaultController::index'], [], [['text', '/']], [], []],
];
